# -*- coding: utf-8 -*-
"""clasificacion_iris

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11Nc_gq2Y2-UI1EAHMMRvbZ1drgS_X33W
"""

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Cargar dataset
data = load_iris()
X = data.data[:, :2]
y = data.target

# Dividir datos
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Modelo
model = LogisticRegression()
model.fit(X_train, y_train)

# Predicciones
y_pred = model.predict(X_test)

# Precisión
accuracy = accuracy_score(y_test, y_pred)
print(f'Precisión del modelo: {accuracy:.2f}')

# Visualización
df = pd.DataFrame({
    'Longitud del Sépalo': X_test[:, 0],
    'Ancho del Sépalo': X_test[:, 1],
    'Especie Real': y_test,
    'Especie Predicha': y_pred
})

plt.figure(figsize=(10, 6))
sns.scatterplot(x='Longitud del Sépalo', y='Ancho del Sépalo', hue='Especie Real', data=df, palette='deep', style='Especie Real')
sns.scatterplot(x='Longitud del Sépalo', y='Ancho del Sépalo', hue='Especie Predicha', data=df, palette='dark', marker='X', s=100)
plt.title('Clasificación - Especies Reales vs Predichas')
plt.xlabel('Longitud del Sépalo')
plt.ylabel('Ancho del Sépalo')
plt.legend(title='Leyenda')
plt.show()